# Automatically generated by HonestCode
# Do not edit this file as it will be overwritten

Feature: Login
  As a Reg user, I want to login on site.

  Scenario: Login successful
    Given I am on my "Home page"
    When I use "Coucou"
    And I click on "login button"
    Then I am redirected to the "Discover page"
