# Automatically generated by HonestCode
# Do not edit this file as it will be overwritten

Feature: Matchlist

  Scenario: Profile pictures in matchlist
    Given my matchlist contains the following profiles:
      | name   | picture provided |
      | Clara  | no               |
      | Lohi   | yes              |
      | Audrey | no               |
    And I am logged on "Affiny"
    And I am on "Home"
    Then I see the following profiles in my matchlist:
      | name   | placeholder picture |
      | Clara  | yes                 |
      | Lohi   | no                  |
      | Audrey | yes                 |
