# Automatically generated by HonestCode
# Do not edit this file as it will be overwritten

Feature: Login
    Rule: login requires id and password

  Background: Scenario created at 1/22/2019:09:43:13.385
    Given user "blibloblu" exists with password "to0secUr3"

  Scenario: Login successful
    Given I am on "Home Page"
    When I log as user "blibloblu" with password "to0secUr3"
    Then login succeeds
    And I am on "Discover"

  Scenario: Wrong password
    Given I am on "Home Page"
    When I log as user "blibloblu" with password "badPassword"
    Then login fails
    And I am on "Home Page"

  Scenario: User unknown
    Given I am on "Home Page"
    When I log as user "userUnknown" with password "whatever"
    Then login fails
    And I am on "Home Page"
