# Automatically generated by HonestCode
# Do not edit this file as it will be overwritten

Feature: login
  As a Reg user, I want to login on site.

  Scenario: Login successful
    Given I am on "Home page"
    When I log with user "coco" and password "Azertyu1"
    And I click on "login button"
    Then I'm redirected to "Discover page"
